"""Added non-nullable constraints for Recipe

Revision ID: 976419b6bf69
Revises: 0d09bdb22690
Create Date: 2025-04-01 21:03:49.230309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976419b6bf69'
down_revision = '0d09bdb22690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_recipes_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_recipes_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
